### ISSUE TITLE
create gh-pages branch if it doesn't exist

### ISSUE THREAD

**Issue by maxogden** [meandavejustice/gh-pages-deploy#5]
currently in a repo w/o `gh-pages` branch created you get:

```
gh-pages-deploy:stdout: 
gh-pages-deploy:stderr: error: pathspec 'gh-pages' did not match any file(s) known to git.

gh-pages-deploy:error: Error: Command failed: error: pathspec 'gh-pages' did not match any file(s) known to git.
```

it might be as simple as changing the first command from `git checkout gh-pages` to `git checkout -b gh-pages`

**Comment by schickling** [comment]
Still not working for me...

**Comment by meandavejustice** [comment]
@schickling Can you tell me a little bit more about your repository when this failed for you?

The only time I have seen `git branch -f` fail is after `git init` has just been run with no files added or committed to git.

[example here](http://stackoverflow.com/questions/9162271/fatal-not-a-valid-object-name-master)

**Comment by schickling** [comment]
Scenario:

1. Create new repo (no `gh-pages` branch existent)
2. Install `gh-pages-deploy`
3. `npm run gh-pages-deploy`

Step 3 fails because `gh-pages` doesn't exist.

**Comment by meandavejustice** [comment]
It sounds like it is failing because no files have been added and committed to git yet, I should add a message which notifies the user of this if it fails in this scenario.

**Comment by meandavejustice** [comment]
For now, try making sure you have an initial commit before running `gh-pages`.

**Comment by schickling** [comment]
Thanks for your help @meandavejustice.

**Comment by meandavejustice** [comment]
@schickling I still need to dig a bit deeper, but I just pushed a new version which allows you to recover(reset head and checkout master) or handle it yourself when there is an error. Hope that helps :)

**Comment by schickling** [comment]
Thanks. I'll let you know if I'm still facing issues!

**Comment by gr2m** [comment]
I've updated to `0.2.0`, and when I run the commands it tells by hand, it all works fine. But when I run the command itself, I get this:

```
Preparing to deploy to gh-pages with these commands: 

 git branch -f gh-pages && 

git checkout gh-pages && 

cp -r docs/* .

git reset --hard origin/master && 

git add -A . && git commit -a -m 'gh-pages update' && 

git push origin gh-pages --force && git checkout master

prompt: There was an error. Would you like to try and recover your original state? (Y/N):  
```

Btw, I've set `"noprompt": true`, but it's still prompting me. As I want this to run on travis, it will cause the build to timeout.

**Comment by gr2m** [comment]
I thought it might be the missing ` && ` after `cp -r docs/* .`, but it's not it, I still get the error (`Process exited with code: 2`). When I copy & paste all the commands it works just fine, I can't tell which line is causing the problem.

**Comment by meandavejustice** [comment]
@gr2m Just pushed an update fixing the build issues and tested against your `humble-localstorage` repo. You will want to bump to version `0.3.0`. The `noprompt` now actually removes all prompts too.

Thank you for catching this!

**Comment by gr2m** [comment]
That's great, thanks for fixing it so fast :)
